const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const correctionPanSchema = new Schema({
  pannumber: String,
  category: String,
  date: Date,
  city: String,
  area_code: String,
  aotype: String,
  range_code: String,
  ao_no: String,
  title: String,
  last_name: String,
  first_name: String,
  middle_name: String,
  name_on_card: String,
  gender: String,
  dob: Date,
  single_parent: String,
  mother_last_name: String,
  mother_first_name: String,
  mother_middle_name: String,
  father_last_name: String,
  father_first_name: String,
  father_middle_name: String,
  name_on_card_parent: String,
  address_type: String,
  flat: String,
  building: String,
  street: String,
  locality: String,
  town: String,
  state: String,
  pincode: String,
  country: String,
  isd_code: String,
  mobile: String,
  email: String,
  aadhaar: String,
  income_source: String,
  identity_proof: [String],
  address_proof: [String],
  dob_proof: [String],
  declaration: String,
  verifier_name: String,
  verification_place: String,
  verification_date: Date,
  image: String,
  file: String,
  signature: String,
  documents: String,
  pan_option: String,
  uniqueId: String,
  pan_status: String,
});

const CorrectionPan = mongoose.models.CorrectionPan || mongoose.model('CorrectionPan', correctionPanSchema);

module.exports = CorrectionPan;
